---
- name: Pull backup from all servers.  Only backs up boot and the default profile in /sketch. 
  
  hosts: emberos
  remote_user: pi

  tasks:
  - name: Ensure local directories
    ansible.builtin.file:
      path: machines/{{ansible_hostname}}/{{ item }}/
      state: directory
    register: local_dir
    delegate_to: localhost
    loop:
      - boot
      - root


  - name: Pull the backup of /boot
    synchronize:
      src: /boot/
      dest: machines/{{ansible_hostname}}/boot/
      checksum: yes
      mode: pull
      #Things that presumably *could* be wanted
      #See the top 2 lines if you want to not back up the networks.
      rsync_opts:
        #- "--exclude=networks/**"
        - "--include=*.nmconnection"
        - "--include=*.ini"
        - "--include=*.yaml"
        - "--include=*.txt"
        - "--include=*.xml"
        - "--include=*.conf"
        - "--include=*.png"
        - "--include=*.jpg"
        - "--include=*.py"
        - "--include=*.sh"
        - "--exclude=*"
        - "--prune-empty-dirs"
    become: yes


  - name: Pull the backup of /sketch/profiles/default/
    synchronize:
      src: /sketch/profiles/default/
      dest: machines/{{ansible_hostname}}/root/
      checksum: yes
      mode: pull
      rsync_opts:
        - "--exclude-from=ignore.txt"
    become: yes
