---
- name: Push backups from all servers
  
  hosts: emberos
  remote_user: pi

  tasks:

  - name: Push the backup of /boot
    synchronize:
      dest: /boot/
      src: machines/{{ansible_hostname}}/boot/
      checksum: yes
      mode: push
      rsync_opts:
        - "--no-perms"
        - "--no-owner"
        - "--no-group"

    become: yes

  - name: Push the backup of /sketch
    synchronize:
      dest: /sketch/
      src: machines/{{ansible_hostname}}/boot/
      checksum: yes
      mode: push
    become: yes
  
  - name: Push the time zones from local controller system time(This is frequently updated data)
    synchronize:
      dest: /usr/share/zoneinfo/
      src:  /usr/share/zoneinfo/
      checksum: yes
      times: yes
      mode: push
      rsync_opts:
        - "--update"

    become: yes
