#!/bin/bash

set -x
set -e


apt-get -y install chrony

#Update timezones
apt-get -y install tzdata

#Pre populate sketch
mkdir -p /sketch/config/timezones


cp /etc/timezone /sketch/config/timezone
cp -a /usr/share/zoneinfo/. /sketch/config/timezones



cat << EOF > /etc/chrony/chrony.conf

# Welcome to the chrony configuration file. See chrony.conf(5) for more
# information about usuable directives.
pool 2.debian.pool.ntp.org iburst

# This directive specify the location of the file containing ID/key pairs for
# NTP authentication.
keyfile /etc/chrony/chrony.keys

# This directive specify the file into which chronyd will store the rate
# information.
driftfile /var/lib/chrony/chrony.drift

# Uncomment the following line to turn logging on.
#log tracking measurements statistics

# Log files location.
logdir /var/log/chrony

# Stop bad estimates upsetting machine clock.
maxupdateskew 100.0

# This directive enables kernel synchronisation (every 11 minutes) of the
# real-time clock. Note that it can’t be used along with the 'rtcfile' directive.
rtcsync

# Step the system clock instead of slewing it if the adjustment is larger than
# one second, but only in the first three clock updates.
makestep 1 3

allow

local stratum 14 orphan
EOF


cat << 'EOF' > /usr/bin/manage_timezones.sh
#!/bin/bash
set -e


# Now set the timezone based on the sketch

#Do a lookup
cp -L /usr/share/zoneinfo/$(cat /sketch/config/timezone|xargs) /dev/shm/localtime
mount --bind /dev/shm/localtime /etc/localtime
chmod 755 /dev/shm/localtime

#Check if system time is older than the newest file in /sketch. If it is, set system time to that time.
#This allows approximately setting the time, to within a few minutes(Good enough to get SSL working),
#By writing anything on the card, but only in its root dir because we don't want to spend a bazillion years
#Scanning the entire card.

set fakertc $(date -r $(find /sketch --maxdepth 1 -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "))
if [ "$(date -d $fakertc +%s)" -gt "$(date +%s)" ]; then
    date -s $fakertc
fi

EOF

chmod 744 /usr/bin/manage_timezones.sh

cat << EOF > /sketch/config/filesystem/emberos_time.yaml
#This relies on the fact that the OS already configures this to be 0755
/sketch/config:
    bindfiles:
        timezone: /etc/timezone
        timezones: /usr/share/zoneinfo

EOF

cat << EOF > /etc/systemd/system/manage_timezones.service
[Unit]
Description=Manage timezones
After=systemd-remount-fs.service fs_bindings.service
Before=sysinit.target chronyd.service
RequiresMountsFor=/etc/ /sketch/
DefaultDependencies=no

[Service]
Type=oneshot
ExecStart=/usr/bin/manage_timezones.sh

[Install]
WantedBy=sysinit.target

EOF

chmod 744 /etc/systemd/system/manage_timezones.service
systemctl enable /etc/systemd/system/manage_timezones.service
