#!/usr/bin/env bash

renice -n 18 $$
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export DIST_PATH=${DIR}
export CUSTOM_PI_OS_PATH=${DIR}/../CustomPiOS/src
export PATH=$PATH:$CUSTOM_PI_OS_PATH

eatmydata tmux -c ${CUSTOM_PI_OS_PATH}/build_custom_os $@
