#!/bin/bash

# Source error handling, leave this in place
set -x
set -e


source /common.sh



# sudo apt-get -y install dirmngr
# gpg --fetch-keys https://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/key.txt
# gpg --export 569130E8CA20FBC4CB3FDE555898470A764B32C9 | sudo apt-key add -
# echo 'deb http://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/ debian yggdrasil' | sudo tee /etc/apt/sources.list.d/yggdrasil.list
# sudo apt-get -y update
# sudo apt-get -y install yggdrasil
# sudo systemctl enable yggdrasil



apt-get -y install network-manager
apt-get -y install libnss3-tools
systemctl enable NetworkManager.service
unpack /filesystem/networkmanager /etc/NetworkManager root



unpack /filesystem/systemd /etc/systemd/system root
unpack /filesystem/bin /usr/bin root

chmod 744 /usr/bin/emberos_netcfg.sh
chmod 755 /usr/bin/nss-systemcerts-import

mkdir -p /etc/pki/nssdb

systemctl enable emberos_netcfg.service

#Update ssl certs
apt-get -y install ca-certificates

#Copy to sketch folder
mkdir -p /sketch/config/sslcerts
mkdir -p /sketch/config/sslcerts.local
mkdir -p /usr/local/share/ca-certificates

cp  -La /usr/share/ca-certificates/. /sketch/config/sslcerts
cp  -La /usr/local/share/ca-certificates /sketch/config/sslcerts.local

cp  /etc/ca-certificates.conf /sketch/config/ca-certificates.conf

#Bind to /etc
cat << EOF > /sketch/config/filesystem/emberos_ssl.yaml
/sketch/config/:
   bindfiles:
    /sketch/config/sslcerts: /usr/share/ca-certificates/
    /sketch/config/sslcerts.local: /usr/local/share/ca-certificates
    /sketch/config/ca-certificates.conf: /etc/ca-certificates.conf
EOF


####################### Setup the firewall ##################################
sudo apt-get -y install nftables
sudo apt-get -y install firewalld
unpack /filesystem/firewalld /etc/firewalld/ root


mkdir -p  /sketch/config/firewalld/
cp -ar /etc/firewalld/. /sketch/config/firewalld

systemctl enable firewalld.service



###### Make NetworkManager sketchified

cat << EOF > /sketch/config/filesystem/emberos_networks.yaml
/sketch/networks/:
    mode: '0600'
    user: root
    bindat: /etc/NetworkManager/system-connections
EOF

apt-get -y install avahi-daemon 
apt-get -y install avahi-utils

# Try to fix the kinds of bugs that are fixable by an Avahi restart
# https://bugs.launchpad.net/ubuntu/+source/avahi/+bug/624043
chmod 755 /usr/bin/restart_avahi.sh
chmod 744 /etc/systemd/system/restart_avahi.service
systemctl enable /etc/systemd/system/restart_avahi.service




unpack /filesystem/avahi /etc/avahi/ root




# Which one? Both? Seems to work!
! systemctl disable dhcpcd.service
! systemctl disable dhcpcd5.service

mkdir -p /sketch/networks
unpack /filesystem/networks /sketch/networks root


