#!/bin/bash

# Source error handling, leave this in place
set -x
set -e


source /common.sh

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+"$LD_LIBRARY_PATH:"}/usr/lib/libeatmydata
export LD_PRELOAD=${LD_PRELOAD:+"$LD_PRELOAD "}libeatmydata.so



sudo apt-get -y install tor
systemctl disable tor.service


#Mesh neetworking!!!
sudo apt-get -y install dirmngr
#gpg --fetch-keys https://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/key.txt
#gpg --export 569130E8CA20FBC4CB3FDE555898470A764B32C9 | sudo apt-key add -
sudo cp /filesystem/569130E8CA20FBC4CB3FDE555898470A764B32C9.pubkey /etc/apt/trusted.gpg.d/yggdrasil.gpg
echo 'deb http://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/ debian yggdrasil' | sudo tee /etc/apt/sources.list.d/yggdrasil.list
sudo apt update

apt-get -y install yggdrasil

# Don't even think about setting this up without
# some serious firewalling(See below, but we still should probably not enable this by default for various reasons)
! systemctl disable yggdrasil

! rm /etc/yggdrasil.conf


mkdir -p /boot/networks/
cp /filesystem/networks/wifi /boot/networks/boot_dir_wifi







#This will let u set up networks from /boot as well as /sketch
cat << 'EOF' > /bin/ember-copy-boot-net.sh
#!/bin/bash

mkdir -p /run/NetworkManager/system-connections/
rsync /boot/networks/ /run/NetworkManager/system-connections/
EOF

chmod 755 /bin/ember-copy-boot-net.sh

cat << EOF > /etc/systemd/system/ember-copy-boot-net.service
[Unit]
Description=Manage things from sketch folder
After=systemd-remount-fs.service
Before=NetworkManager.service
RequiresMountsFor=/sketch/ /boot/

[Service]
Type=oneshot
ExecStart=/bin/ember-copy-boot-net.sh

[Install]
WantedBy=sysinit.target

EOF
systemctl enable ember-copy-boot-net.service


# This little piece of old garbage crashes everything when it sees you have switched to networkmanager and can't find it's stuff,
# because it still runs and fills ram with log files.
apt-get -y remove dhcpcd-gtk

apt-get -y install network-manager libnss3-tools ca-certificates nftables firewalld avahi-daemon avahi-utils radvd

apt-get -y install network-manager-gnome

systemctl disable wpa_supplicant.service
systemctl mask wpa_supplicant.service

systemctl enable NetworkManager.service
unpack /filesystem/networkmanager /etc/NetworkManager root



unpack /filesystem/systemd /etc/systemd/system root
unpack /filesystem/bin /usr/bin root



mkdir -p /etc/pki/nssdb








mkdir -p /var/lib/blueman



####################### Setup the firewall ##################################
unpack /filesystem/firewalld /etc/firewalld/ root

systemctl enable firewalld.service


#Yggdrasil and cjdns get firewalled to public
#SSH gets blocked from public, we don't want any hacking
mkdir -p /etc/firewalld/zones/
cat << EOF > /etc/firewalld/zones/public.xml
<?xml version="1.0" encoding="utf-8"?>
<zone target="%%REJECT%%">
  <short>Public</short>
  <description>For use in public areas. You do not trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted.</description>
  <source address="300::/8"/>
  <source address="200::/8"/>
  <source address="fc00::/8"/>
  <service name="dhcpv6-client"/>
  <port port="123" protocol="udp"/>
</zone>
EOF

cat << EOF > /etc/systemd/system/nmbd.service
[Unit]
Description=Samba NMB Daemon
Documentation=man:nmbd(8) man:samba(7) man:smb.conf(5)
Wants=network-online.target
After=network.target network-online.target

[Service]
Type=notify
PIDFile=/run/samba/nmbd.pid
EnvironmentFile=-/etc/default/samba
ExecStart=/usr/sbin/nmbd --foreground --no-process-group $NMBDOPTIONS
ExecReload=/bin/kill -HUP $MAINPID
LimitCORE=infinity
Restart=on-failure
RestartSec=600s

[Install]
WantedBy=multi-user.target
EOF


# Try to fix the kinds of bugs that are fixable by an Avahi restart
# https://bugs.launchpad.net/ubuntu/+source/avahi/+bug/624043
chmod 755 /usr/bin/restart_avahi.sh
chmod 744 /etc/systemd/system/restart_avahi.service
systemctl enable /etc/systemd/system/restart_avahi.service




unpack /filesystem/avahi /etc/avahi/ root




# Which one? Both? Seems to work!
! systemctl disable dhcpcd.service
! systemctl disable dhcpcd5.service
! systemctl mask dhcpcd.service
! systemctl mask dhcpcd5.service

! systemctl unmask wpa_supplicant.service


! sudo apt purge -y openresolv
! sudo apt purge -y dhcpcd5

mkdir -p /sketch/profiles/default/etc/NetworkManager/system-connections
unpack /filesystem/networks /sketch/profiles/default/etc/NetworkManager/system-connections/ root

chmod 700 /sketch/profiles/default/etc/NetworkManager/system-connections
chmod 600 /sketch/profiles/default/etc/NetworkManager/system-connections/*
