#!/bin/bash

# Source error handling, leave this in place
set -x
set -e


source /common.sh



# sudo apt-get -y install dirmngr
# gpg --fetch-keys https://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/key.txt
# gpg --export 569130E8CA20FBC4CB3FDE555898470A764B32C9 | sudo apt-key add -
# echo 'deb http://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/ debian yggdrasil' | sudo tee /etc/apt/sources.list.d/yggdrasil.list
# sudo apt-get -y update
# sudo apt-get -y install yggdrasil
# sudo systemctl enable yggdrasil



apt -y install network-manager
systemctl enable NetworkManager.service
unpack /filesystem/networkmanager /etc/NetworkManager root



unpack /filesystem/systemd /etc/systemd/system root
unpack /filesystem/bin /usr/bin root

chmod 744 /usr/bin/emberos_netcfg.sh

systemctl enable emberos_netcfg.service




####################### Setup the firewall ##################################
sudo apt -y install nftables
sudo apt -y install firewalld
unpack /filesystem/firewalld /etc/firewalld/ root


mkdir -p  /sketch/config/firewalld/
cp -ar /etc/firewalld/. /sketch/config/firewalld

systemctl enable firewalld.service



###### Make NetworkManager sketchified


chmod 744 /usr/bin/networkmanager_sketch.sh


chmod 744 /etc/systemd/system/networkmanager_sketch.service
systemctl enable /etc/systemd/system/networkmanager_sketch.service



apt -y install avahi-daemon 
apt -y install avahi-utils

# Try to fix the kinds of bugs that are fixable by an Avahi restart
# https://bugs.launchpad.net/ubuntu/+source/avahi/+bug/624043
chmod 755 /usr/bin/restart_avahi.sh
chmod 744 /etc/systemd/system/restart_avahi.service
systemctl enable /etc/systemd/system/restart_avahi.service



#Update ssl certs
apt -y install ca-certificates

#Copy to sketch folder
mkdir -p /sketch/config/sslcerts
cp  -La /etc/ssl/certs/. /sketch/config/sslcerts

unpack /filesystem/avahi /etc/avahi/ root




# Which one? Both? Seems to work!
! systemctl disable dhcpcd.service
! systemctl disable dhcpcd5.service

mkdir -p /sketch/networks
unpack /filesystem/networks /sketch/networks root


