#!/bin/bash

set -x
set -e

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+"$LD_LIBRARY_PATH:"}/usr/lib/libeatmydata
export LD_PRELOAD=${LD_PRELOAD:+"$LD_PRELOAD "}libeatmydata.so

#Games
apt-get -y install mednaffe  brandy bwbasic kolourpaint sl cmatrix

if [ -z "$EMBER_MICRO" ]
then
! apt-get -y install gnome-games
! apt-get -y install abe
! apt-get -y install crawl-tiles
! apt-get -y install circuslinux
! apt-get -y install xbubble
! apt-get -y install tomatoes
! apt-get -y install dossizola
! apt-get -y install gnome-mastermind
! apt-get -y install ardentryst
! apt-get -y install open-invaders
! apt-get -y install monsterz
! apt-get -y install klavaro
! apt-get -y install flobopuyo


# ! apt-get -y --no-install-recommends install performous
# ! apt-get -y install performous-composer


cat << EOF > /usr/share/applications/XBubble.desktop
[Desktop Entry]
Name=Bubbles
Type=Application
Exec=xbubble
Terminal=false
Categories=Game;
EOF

# ! apt-get -y install pianobooster
# cat << EOF > /usr/share/applications/pbsnd.desktop
# [Desktop Entry]
# Name=PianoBooster(w/sound)
# Type=Application
# Exec=bash -c "qsynth& pianobooster"
# Terminal=false
# Categories=Game;
# EOF


#! apt-get -y install geekcode


# All these are done through the included data pack now, since we focus on MineClone2
apt-get -y install minetest

systemctl disable minetest-server

# ! apt-get -y install pinball
! apt-get -y install njam
! apt-get -y install brainparty
! apt-get -y install qxw
! apt-get -y install golly
! apt-get -y install alex4
! apt-get -y install gnubik


cd /build_cache

# wget -O -nc https://github.com/TeamRizu/OutFox/releases/download/OF4.14.1/OutFox-alpha-0.4.14.1HF-RPi-Linux-arm32v7-date-20220327.tar.gz

# mkdir /opt/OutFox
# cd /opt/OutFox

# tar -xvf  /build_cache/OutFox-alpha-0.4.14.1HF-RPi-Linux-arm32v7-date-20220327.tar.gz  --strip-components=1


# cat << EOF > /usr/share/applications/OutFox.desktop
# [Desktop Entry]
# Type=Application
# Name=Project OutFox Dance
# Icon=/home/mtk/Desktop/Icons/dance_icon.png
# Exec=/opt/OutFox/OutFox
# Categories=Game

# EOF


fi

cd /build_cache

