#!/bin/bash

set -x
set -e

source /common.sh

mkdir -p /sketch/kaithem/

if [ ! -d /build_cache/KaithemAutomation ]
then
git clone --depth 1 https://github.com/EternityForest/KaithemAutomation.git /build_cache/KaithemAutomation
else
cd /build_cache/KaithemAutomation
git pull --rebase
fi

git clone --depth 1 /build_cache/KaithemAutomation /opt/kaithem

cd /opt/kaithem/


git remote set-url origin https://github.com/EternityForest/KaithemAutomation.git

rsync -avz /opt/kaithem/kaithem/var/  /sketch/kaithem/

unpack /filesystem/kaithem_sketch/ /sketch/kaithem/ root

unpack /filesystem/systemd/ /usr/lib/systemd/system/ root

#Remove dummy keys so the user can add them if missing
! rm /sketch/kaithem/ssl/certificate.key
! rm /sketch/kaithem/ssl/certificate.cert

chmod a+x /opt/kaithem/ /opt/kaithem/kaithem/kaithem.py


cat << EOF > /sketch/kaithem/registry/data/jacksettings.yaml
{jackDevice: '', jackMode: dummy, jackPeriodSize: 256, jackPeriods: 2, sharePulse: 'off',
  usbLatency: -1, usbPeriodSize: 256, usbPeriods: 3, usbQuality: 0, useAdditionalSoundcards: 'yes'}
EOF