#!/bin/bash

usermod --shell /usr/bin/xonsh pi


rm -rf /tmp/*
rm -rf /var/tmp/*
rm -rf /var/log/*
apt-get reinstall shared-mime-info
update-mime-database /usr/share/mime
chmod -R o+r /usr/share/mime
