#!/bin/bash

usermod --shell /usr/bin/xonsh pi


rm -rf /tmp/*
rm -rf /var/tmp/*
rm -rf /var/log/*
apt-get -y reinstall shared-mime-info

! rm -rf /home/pi/.cache/yarn

#Restore Yarn settings
yarn config set cache-folder /usr/local/share/.cache/yarn



#This was like somehow getting undone?????
touch /etc/pipewire/media-session.d/with-jack
cp /usr/share/doc/pipewire/examples/ld.so.conf.d/pipewire-jack-*.conf /etc/ld.so.conf.d/
ldconfig

! rm /etc/machine-id




mkdir -p /sketch/profiles/default/etc/NetworkManager/system-connections
rsync -avz /etc/NetworkManager/system-connections/ /sketch/profiles/default/etc/NetworkManager/system-connections/

cp /etc/hostname /sketch/profiles/default/etc/hostname
cp /etc/hosts /sketch/profiles/default/etc/hosts



mkdir -p /sketch/profiles/default/home/pi/kaithem
mkdir -p /sketch/profiles/default/etc/ember-autostart
mkdir -p /sketch/profiles/default/var/www/html

rsync -avz /etc/ember-autostart/ /sketch/profiles/default/etc/ember-autostart/

# This is supposed to be unique
! rm /etc/machine-id
touch /etc/machine-id

# Make unwritable till the mounts get there
chmod 555 /var/tmp
chmod 555 /tmp
chown -R pi /sketch/profiles/default/home/pi

chown -R pi /home/pi
chown root /sketch

# Undo what we did.
mv /bin/udevadm-hidden /bin/udevadm
