#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

#Force IPv4 for apt updates until such a time as ipv6 is supported everywhere.
echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99-force-ipv4

apt update -y --allow-releaseinfo-change
apt update

unpack /filesystem/sketch /sketch




apt-get -y install -y ntfs-3g
#Very important!!! Fuse and Fuse3 have a horrible incompatibility because of -o nonempty
apt-get -y install -y bindfs fuse3
#Needed for reading config files
apt-get -y install -y python3-yaml


#The special /sketch partition is for everything that is not part of the image. It is made after the fact.
! mkdir /sketch

raspi-config nonint do_ssh 0
raspi-config nonint do_spi 0
raspi-config nonint do_i2c 0
raspi-config nonint do_camera 0

raspi-config nonint do_overscan 1
#https://www.bountysource.com/issues/35286369-disabling-serial-removes-dev-ttyacm0
raspi-config nonint do_serial 1
raspi-config nonint set_config_var enable_uart 1 /boot/config.txt


#Set up for a US keyboard by default
sudo raspi-config nonint do_change_locale en_US.UTF-8 UTF-8
raspi-config nonint do_configure_keyboard us


#Here's what the old one was
# proc            /proc           proc    defaults          0       0
# PARTUUID=f7a89ab5-01  /boot           vfat    defaults          0       2
# PARTUUID=f7a89ab5-02  /               ext4    defaults,noatime  0       1


## Warning: This just overwrites it entirely. Future versions of raspbian
## Might have some other system FS stuff they need here.

mkdir -p /home/pi/.ssh
mkdir -p /root/.ssh


## 
cat << EOF > /etc/fstab
proc            /proc           proc    defaults          0       0
/dev/mmcblk0p1  /boot           vfat    defaults,noatime,ro          0       2
/dev/mmcblk0p2  /               ext4    defaults,noatime,ro  0       1
/dev/mmcblk0p3 /sketch auto defaults,noatime,nofail,fmask=027,dmask=027,umask=027 0 0
EOF






mkdir -p /var/www/html/
cat << EOF > /var/www/html/index.html

<h1 id="welcome-to-emberos">Welcome to EmberOS</h1>
<p>This is the kiosk start page. It is served from /sketch/kiosk_startpage.html.</p>
<p>You can of course exit back to the shell with Alt+F4</p>
EOF

#Generate an RSA key whenever it does not exist, if we can
#Then move whatever kets we find into the SSH ramdisk.

cat << 'EOF' > /usr/bin/manage_sketch_folder.sh
#!/bin/bash

#This script generates nonexistant keys, and
#Also moves keys into the special tmpfs just for those keys.

#It also binds apache's www stuff
set -e

mkdir -p /sketch/config

mkdir -p /dev/shm/roothome
mkdir -p /dev/shm/roothome_work


chmod 700 /dev/shm/roothome
chmod 700 /dev/shm/roothome_work


mkdir -p  /sketch/ssh/pi
mkdir -p /sketch/ssh/root

if [ ! -f /sketch/ssh/pi/id_rsa ]; then
    cat /dev/zero | ssh-keygen -f /sketch/ssh/pi/id_rsa -q -N ""
fi

if [ ! -f /sketch/ssh/pi/authorized_keys ]; then
    touch /sketch/ssh/pi/authorized_keys
fi

if [ ! -f /sketch/ssh/root/id_rsa ]; then
    cat /dev/zero | ssh-keygen -f /sketch/ssh/root/id_rsa -q -N ""
fi

if [ ! -f /sketch/ssh/root/authorized_keys ]; then
    touch /sketch/ssh/root/authorized_keys
fi

mount -t overlay -o lowerdir=/root,upperdir=/dev/shm/roothome,workdir=/dev/shm/roothome_work overlay /root



#Use what is already there as the template
if [ ! -d /sketch/public.www ]; then
    mkdir /sketch/public.www
    cp -a /var/www/html/. /sketch/public.www/
fi



#Use what is already there as the template
if [ ! -d /sketch/public.files ]; then
    mkdir /sketch/public.files
fi

#Use what is already there as the template
if [ ! -d /sketch/public.media ]; then
    mkdir /sketch/public.media
fi

#We want to be robust against someone deleting that file
if [ ! -f /sketch/config.private/yggdrasil.conf ]; then
! yggdrasil -genconf -json > /sketch/config.private/yggdrasil.conf
fi

#Generate missing SSL keys
if [ ! -f /sketch/kaithem/ssl/certificate.key ] ; then
    mkdir -p /sketch/kaithem/ssl/
    #Look at this race condition here! Someone could steal that private key before we chmod it!
    openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /sketch/kaithem/ssl/certificate.key  -out  /sketch/kaithem/ssl/certificate.cert -subj '/CN=localhost'
    
    #Copy it so it's trusted by browsers
    mkdir -p /sketch/config/sslcerts.local/
    mkdir -p /sketch/config/sslcerts.local/ember-kaithem
    #Yes, the filename mismatch is intentional!!
    cp /sketch/kaithem/ssl/certificate.cert /sketch/config/sslcerts.local/ember-kaithem/kaithem_localhost.crt
fi
EOF

chmod 744 /usr/bin/manage_sketch_folder.sh



cat << EOF > /etc/systemd/system/manage_sketch_folder.service
[Unit]
Description=Manage things from sketch folder
After=systemd-remount-fs.service 
#Before fs_bindings, it sets up the stuff that we are binding.
Before=sysinit.target fs_bindings.service
RequiresMountsFor=/etc/ /sketch/ /home/
DefaultDependencies=no

[Service]
Type=oneshot
ExecStart=/usr/bin/manage_sketch_folder.sh

[Install]
WantedBy=sysinit.target

EOF

chmod 744 /etc/systemd/system/manage_sketch_folder.service
systemctl enable /etc/systemd/system/manage_sketch_folder.service





unpack /filesystem/systemd /etc/systemd/system root
unpack /filesystem/bin /usr/bin root 

chmod 744 /etc/systemd/system/fs_bindings.service
chmod 744 /usr/bin/fs_bindings.py
systemctl enable /etc/systemd/system/fs_bindings.service

chmod 744 /etc/systemd/system/runprovisioning.service
chmod 744 /usr/bin/runprovisioning.py
systemctl enable /etc/systemd/system/runprovisioning.service

chmod 744 /etc/systemd/system/serviceconfig.service
chmod 744 /usr/bin/serviceconfig.py
systemctl enable /etc/systemd/system/serviceconfig.service



mkdir -p /sketch/config/filesystem
mkdir -p /root/ssh

#Can't be in the config dir because there is keys in there
mkdir -p /sketch/ssh/etc.ssh

cp -a /etc/ssh/ssh_config  /sketch/ssh/etc.ssh/ssh_config

mkdir -p  /sketch/ssh/pi
mkdir -p /sketch/ssh/root


cat << EOF > /sketch/config/filesystem/emberos_sshconf.yaml
/sketch/ssh/etc.ssh:
    mode: '0700'
    user: root
    bindat: /etc/ssh

/sketch/ssh/pi/:
    mode: '0700'
    user: pi
    bindat: /home/pi/.ssh

/sketch/ssh/root: /root/.ssh/
EOF

cat << EOF > /sketch/config/filesystem/readme.md

The bind manager tool takes config files like


    /sketch/config:
        bindat: /etc/sketchconfig

and 


    /sketch/config:
        bindfiles:
            hosts: /etc/hosts
            hostname: /etc/hostname

    /sketch/config/simple: /simple

and merges them together, then uses them to set up bindings.

In this case we are saying: Make /sketch/config viewable at /etc/sketchconfig.

in the second file, we say(Note relative paths), make /etc/sketchconfig/hosts viewable at /etc/hosts

Bindfiles are relative to the main bindat location for that path, or the first configured parent path

## Simple Bindings

The line "/sketch/config/simple: /simple"
binds  /etc/sketchconfig/simple to /simple,
because the path gets rebased on the first configured parent.


EOF

mkdir -p /home/pi/public.files
mkdir -p /home/pi/public.media

#General purpose private persistant area
mkdir -p /sketch/home/pi
mkdir -p /home/pi/persist


cat << EOF > /home/pi/KIOSK_INFO_README_IMPORTANT.txt
This is a kiosk UI! For reliability, almost everything in the home dir starts fresh when rebooting.

Anything saved in this home dir, except the persist, public.files, and public.media folders,
will disappear when the device is powered off!!

For convenience, many things are just shortcuts to these directories, and many programs
have been preconfigured to safe important data there, but you should not trust any folder you
did not verify for yourself.

Also note that public.* folders are truly public. Anyone on the local network may be able to read
them.
EOF

mk_pi_persist_dir () {
  mkdir -p "/sketch/home/pi/$1"
  mkdir -p "/home/pi/$1"

  #Move to sketch, delete original
  ! cp -ar "/home/pi/$1/." "/sketch/home/pi/$1"
  ! rm -r  "/home/pi/$1"
  ln -s "/home/pi/persist/$1" "/home/pi/$1"
}


mkdir -p /home/pi/.local/share
chown pi /home/pi/.local/share
mkdir -p /home/pi/.config
chown pi /home/pi/.config

#Symlink some directories that are pretty obviously useful to persist
#But only the super obviously "Manual" ones that aren't messed with by the system
mk_pi_persist_dir  Documents
mk_pi_persist_dir  Pictures
mk_pi_persist_dir  Music
mk_pi_persist_dir  Downloads
mk_pi_persist_dir  Templates
mk_pi_persist_dir  Videos
mk_pi_persist_dir  Arduino
mk_pi_persist_dir  Books
mk_pi_persist_dir  Projects
mk_pi_persist_dir  Maps
mk_pi_persist_dir  Scratch Projects
mk_pi_persist_dir  Misc
mk_pi_persist_dir  Drawer
mk_pi_persist_dir  Games
mk_pi_persist_dir  Sync
mk_pi_persist_dir  "Calibre Library"
mk_pi_persist_dir  .config/calibre
mk_pi_persist_dir  .config/Zeal
mk_pi_persist_dir .local/share/marble
mk_pi_persist_dir .local/share/Zeal

mkdir -p /sketch/home/pi/.local/share/Zeal

mk_pi_persist_dir .config/deluge
mk_pi_persist_dir .config/ardour5
mk_pi_persist_dir .config/sigrok
mk_pi_persist_dir .kodi

#This one is annoying, it saves EVERYTHING
#to the same session file on exit. But whatever, it's only
#30kb, probably not a significant issue
mk_pi_persist_dir .config/spacefm

mk_pi_persist_dir .wiki_indexes

#Youtube client
mk_pi_persist_dir tartube_data

mk_pi_persist_dir  .fonts
mk_pi_persist_dir  .home_template
mk_pi_persist_dir  .mednafen
mk_pi_persist_dir  .node-red
mk_pi_persist_dir  .npm
mk_pi_persist_dir  .nimble
mk_pi_persist_dir  .viking
mk_pi_persist_dir  .viking_maps
mk_pi_persist_dir  .fldigi
mk_pi_persist_dir  .flrig
mk_pi_persist_dir  .flmsg
mk_pi_persist_dir  .flamp
mk_pi_persist_dir  .syncthing
mk_pi_persist_dir  .syncthing-gtk
mk_pi_persist_dir .local/share/fonts

#Give pi a place to share public stuff, if desired
mkdir -p /sketch/public.files/pi
mkdir -p /sketch/public.media/pi


mkdir -p /sketch/public.media/Pictures
mkdir -p /sketch/public.media/Music
mkdir -p /sketch/public.media/Videos

#The mountpoint
mkdir -p /var/public.media/
mkdir -p /var/public.files/

#Make the example files more discoverable
ln -s /var/public.media/Music/  "/sketch/home/pi/Music/sketch"
ln -s /var/public.media/Pictures/  "/sketch/home/pi/Pictures/sketch"
ln -s /var/public.media/Videos/  "/sketch/home/pi/Videos/sketch"

cat << EOF > /sketch/config/filesystem/emberos_public.yaml
/sketch/public.files:
    mode: '0755'
    user: root
    bindat: /var/public.files/

/sketch/public.media:
    mode: '0755'
    user: root
    bindat: /var/public.media
EOF



cat << EOF > /sketch/config/filesystem/emberos_public_pi.yaml
/sketch/public.files/pi:
    mode: '0755'
    user: pi
    bindat:  /home/pi/public.files

/sketch/public.media/pi:
    mode: '0755'
    user: pi
    bindat: /home/pi/public.media
EOF


cat << EOF > /sketch/config/filesystem/emberos_pi.yaml

#Creates the tmpfs overlay on top of /home/pi
__tmpfsoverlay__HOMEPI:
    bindat: /home/pi
    mode: '750'
    user: pi



/sketch/home/pi:
    #We want to be able to stash security keys in there, so this must be mode
    #700
    mode: '0700'
    user: pi
    #The tmpfs overlay has to be under the sketch stuff, or it seems to point at the original home dir,
    #and cover up the sketch
    #Once the sketch and the bindat is there we can run this and copy anything we might need
    post_cmd: cp -ar /home/pi/persist/.home_template/. /home/pi
    bindat: /home/pi/persist
EOF

mkdir -p /sketch/share

mkdir -p /sketch.opt
mkdir -p /usr/bin.sketch

mkdir -p /sketch/opt
mkdir -p /sketch/bin
mkdir -p /sketch/share/fonts
mkdir -p /sketch/share/wikis
mkdir -p /sketch/share/doc/

mkdir /usr/share.sketch

cat << EOF > /sketch/config/filesystem/emberos_share.yaml
/sketch/share/:
    mode: '0755'
    bindat: /usr/share.sketch
/sketch/share/fonts: /usr/local/share/fonts
EOF


cat << EOF > /sketch/config/filesystem/emberos_opt_bin.yaml
/sketch/opt/:
    mode: '0755'
    bindat: /sketch.opt
/sketch/bin/:
    mode: '0755'
    bindat: /usr/bin.sketch
EOF

#Allow the /sketch/bin to work
cat << EOF > /usr/lib/environment.d/98-ember-sketch-bin.conf 
PATH=/usr/bin.sketch:$PATH
EOF


mkdir -p /sketch/config.private
mkdir -p /etc/sketchconfig.private

mkdir -p /sketch/config
mkdir -p /etc/sketchconfig

#This is what sets up the main config dir
cat << EOF > /sketch/config/filesystem/emberos_configdir.yaml
/sketch/config/:
    mode: '0755'
    user: root
    bindat: /etc/sketchconfig
/sketch/config.private:
    mode: '0700'
    user: root
    bindat: /etc/sketchconfig.private
EOF
#Disable serial debugging, use readonly mode, and ditch the awful resize on first boot
#Because it won't work and who knows what it will do
cat << EOF > /boot/cmdline.txt
dwc_otg.lpm_enable=0 console=tty1 root=/dev/mmcblk0p2  rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles ro
EOF
! rm etc/rc3.d/S01resize2fs_once
#Don't try to launch graphically by default
systemctl set-default multi-user.target


mkdir -p /sketch/cache/apt/archives
cat << EOF > /sketch/cache/README.md
/sketch/cache/apt/ is equivalent to /var/cache/apt/
EOF
#This is what sets up the main config dir
cat << EOF > /sketch/config/filesystem/emberos_apt.yaml
/sketch/cache/apt/archives:
    mode: '0755'
    user: _apt
    bindat: /var/cache/apt/archives
EOF



unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot root

echo "This is an example module, install and set up what you need here!"
echo "$EMBEDPI_VAR"

# Unpack root at the end, so files are modified before
unpack /filesystem/root /



#These depend on the fact that remounting seems to leave things
#In their place in the layering of mounts
cat << EOF > /usr/bin/writable
#!/bin/bash
mount -o remount,rw /
mount -o remount,rw /boot
mount -o remount,rw /sketch
EOF

cat << EOF > /usr/bin/readonly
#!/bin/bash
mount -o remount,ro /
mount -o remount,ro /boot
EOF

chmod 755 /usr/bin/writable
chmod 755 /usr/bin/readonly


#Hackishly patch this to call readonly first
cat << EOF > /lib/systemd/system/regenerate_ssh_host_keys.service
[Unit]
Description=Regenerate SSH host keys
Before=ssh.service
ConditionFileIsExecutable=/usr/bin/ssh-keygen

[Service]
Type=oneshot
ExecStartPre=-/bin/dd if=/dev/hwrng of=/dev/urandom count=1 bs=4096
ExecStartPre=-/bin/sh -c "/bin/rm -f -v /etc/ssh/ssh_host_*_key*"
ExecStart=/bin/bash -c ' /usr/bin/ssh-keygen -A -v >> /var/log/regenerate_ssh_host_keys.log 2>&1'
ExecStartPost=/bin/bash -c 'for i in /etc/ssh/ssh_host_*_key*; do actualsize=$(wc -c <"$i") ;if [ $actualsize -eq 0 ]; then echo size is 0 bytes ; exit 1 ; fi ; done ; /usr/bin/writable; /bin/systemctl disable regenerate_ssh_host_keys ; /usr/bin/readonly'

[Install]
WantedBy=multi-user.target
EOF
