#!/bin/bash

set -x
set -e


## RPITX HAS BEEN DISABLED FOR NOW. I never actually did get it to work I don't think.

# mkdir -p /sketch/opt/rpitx

# sudo apt-get install -y libsndfile1-dev git
# sudo apt-get install -y imagemagick libfftw3-dev
# sudo apt-get install -y rtl-sdr buffer

# #Hacktasktic awfulness
# mv filesystem/csdr /filesystem/rpitx/

# cd /filesystem/rpitx/
# patch -i csdrpizero.diff csdr/Makefile
# cd csdr/

# make
# make install


# mv /filesystem/librpitx /filesystem/rpitx/src
# cd /filesystem/rpitx/src/librpitx/src
# make

# mv /filesystem/ft8_lib /filesystem/rpitx/src/pift8

# cd /filesystem/rpitx/src/

# make
# sudo make install


# rsync -a --exclude="src" --exclude="csdr" /filesystem/rpitx/ /sketch/opt/rpitx

# ! rm -r /sketch/opt/rpitx/ft8_lib
