#!/bin/bash

set -x
set -e

apt-get -y install mosquitto
echo "persistence false" > /etc/mosquitto/conf.d/emberos.conf

# SyncThing is installed, but not set up!!!
wget -O - https://syncthing.net/release-key.txt > /etc/apt/trusted.gpg.d/syncthing.asc
echo "deb http://apt.syncthing.net/ syncthing release" | sudo tee -a /etc/apt/sources.list.d/syncthing-release.list
sudo apt-get update
sudo apt-get install syncthing -y

mkdir -p /sketch/home/pi/.syncthing
mkdir -p /sketch/home/pi/.syncthing-gtk

#We don't know if the sycthing dir will exist as soon as it's installe
! cp -ar /home/pi/.config/syncthing/. /sketch/home/pi/.syncthing
! cp -ar /home/pi/.config/syncthing-gtk/. /sketch/home/pi/.syncthing-gtk

cat << EOF > /sketch/config/filesystem/emberos_pi_syncthing.yaml
/sketch/home/pi/.syncthing:
    mode: '0700'
    user: pi
    bindat: /home/pi/.config/syncthing/
EOF

#Also gets firewalld
# apt-get -y install firewall-config


apt-get -y install dosbox

mkdir -p /sketch/home/pi/.dosbox
! cp -ar /home/pi/.dosbox/. /sketch/home/pi/.dosbox
! rm -r  /home/pi/.dosbox
ln -s /home/pi/persist/.dosbox /home/pi/.dosbox


apt-get -y install python3-smbus

#Batteries included, allow messing with kiosk browser media right from the device
apt-get -y install gimp audacity
#MP3 Export for Audacity
apt-get install lame -y


apt-get -y install transmission-cli 
apt-get -y install xclip zenmap

apt-get -y install sqlitebrowser
apt-get -y install meld
#Nobody wants to have to develop on a pi. It happens sometimes anyway.
apt-get -y install git-cola

#Always good to have around
apt-get -y install gnome-disk-utility

apt-get -y install unclutter
apt-get -y install imagemagick

apt-get -y install p7zip p7zip-full

apt-get -y install fvwm fvwm-icons

update-icon-caches /usr/share/icons/*

# Installs the Micro editor
# Do this early, it can't be cached like apt
cd /usr/bin/
curl https://getmic.ro | bash

#Useful for testing
apt-get -y install x11-apps

apt-get -y install python3

apt-get -y install exfat-utils
apt-get -y install python3-setproctitle
apt-get -y install python3-cffi
apt-get -y install python3-dbus

#This language is included because of it's excellent dynamic imports in python
apt-get -y install nim


pip3 install yappi
pip3 install msgpack
pip3 install paho-mqtt
pip3 install smbus
pip3 install automationhat

pip3 install cherrypy
pip3 install adafruit-blinka

pip3 install nimport

pip install python-can



mkdir -p /publictemp
mkdir -p /sketch/public.www/
mkdir -p /sketch/public.files/

echo "Welcome! This file is /sketch/public.www/index.html. You can alt+f4 out to a graphical desktop."> /sketch/public.www/index.html

apt-get -y install apache2

mkdir -p /sketch/public.www

#Give www-data a "window into the root filesystem"
cat << EOF > /sketch/config/filesystem/www.yaml
/sketch/public.www:
    mode: '0750'
    user:  www-data
    bindat: /var/www/html
EOF

sudo apt-get install -y php-{bcmath,bz2,intl,gd,mbstring,mcrypt,mysql,zip}
apt-get install libapache2-mod-php -y

apt-get -y install mpv
apt-get -y install libgdk-pixbuf2.0-bin
#All the compilerie you might want
apt-get -y install python3-dev build-essential gcc g++ 

apt-get -y install python3 systemd cython3 build-essential
apt-get -y install mplayer python3-serial
apt-get -y install python3-pyqt5 python3-pyqt5.qtserialport python3-pyqt5.qtsvg python3-pyqt5.qtchart python3-pyqt5.qtmultimedia
apt-get -y install python3-pyqt5.qtsql python3-pyqt5.qtwebkit python3-pyqt5.qtopengl python3-pyqt5.qtsensors
apt-get -y install python3-lxml
apt-get -y install python3-tz python3-dateutil lm-sensors
apt-get -y install python3-netifaces python3-jack-client
apt-get -y install python3-gst-1.0 python3-libnacl jack-tools
apt-get -y install jackd2 gstreamer1.0-plugins-good gstreamer1.0-plugins-bad a2jmidid
apt-get -y install swh-plugins tap-plugins caps  gstreamer1.0-plugins-ugly python3-psutil
#Don't include a giant soundfont, kaithem already has a decent one
apt-get -y install -y --no-install-recommends  fluidsynth

#Better shells
apt-get -y install -y elvish fish

apt-get -y install npm
npm install -g --unsafe-perm node-red

#Coding font
apt-get -y install -y fonts-hack



apt-get -y install -y spacefm fslint

apt-get -y install -y deluge
#Make dir persistent
mkdir -p /sketch/home/pi/.config/deluge
! cp -ar /home/pi/.config/deluge/. /sketch/home/pi/.config/deluge
! rm -r  /home/pi/.config/deluge
ln -s /home/pi/persist/.config/deluge /home/pi/.config/deluge


apt-get -y install -y ardour

mkdir -p /sketch/home/pi/.config/ardour5
! cp -ar /home/pi/.config/ardour5/. /sketch/home/pi/.config/ardour5
! rm -r  /home/pi/.config/ardour5
ln -s /home/pi/persist/.config/ardour5 /home/pi/.config/ardour5

#apt-get -y install -y krita

apt-get -y install -y wireshark


apt-get install pulseview -y

apt-get -y install nmap robotfindskitten
apt-get -y install ncdu
apt-get -y install mc
apt-get -y install curl

#Sigh. Vim is huge but some people really love it...
apt-get -y install vim
#Emacs is huge
#apt-get -y install emacs
apt-get -y install zile
apt-get -y install xcas
apt-get -y install units
apt-get -y install git
apt-get -y install wget
apt-get -y install htop
apt-get -y install lsof
apt-get -y install fzf
apt-get -y install chafa
apt-get -y install nast



#Without this we have all kinds of issues doing startx
apt-get -y install xserver-xorg-legacy

#Allow non-console startx, needed to make kiosk browsing work
#This has to be AFTER the xserver-xorg-legacy to work
sed -i \
    's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config

apt-get -y install fatrace

gtk-update-icon-cache


#Install last so the build doesn't try using it from inside quemu
#And slow everything down by not working
#Currently removed
#apt-get -y install squid-deb-proxy-client



apt-get autoremove -y --purge
