#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export DIST_PATH=${DIR}
export CUSTOM_PI_OS_PATH=/home/daniel/github/CustomPiOS/src
export PATH=$PATH:$CUSTOM_PI_OS_PATH

${CUSTOM_PI_OS_PATH}/build_custom_os $@
