#!/bin/bash

set -e
set -x

source /common.sh

#Copy over the modified hwclock-set.sh
unpack /filesystem/libudev /lib/udev/ root
unpack /filesystem/systemd /etc/systemd/system/ root
unpack /filesystem/bin /bin/ root


chmod 755 /lib/udev/hwclock-set

# This is not needed, chrony does that for us
# chmod 755 /bin/rtcsync.sh
# chmod 744 /etc/systemd/system/rtcsync.timer
# chmod 744 /etc/systemd/system/rtcsync.service

# systemctl enable rtcsync.timer
# systemctl enable rtcsync.service