#!/usr/bin/env bash

# Source error handling, leave this in place
set -x
set -e


source /common.sh


cat << 'EOF' > /sketch/config/sound.ini
#This section configures the pi's onboard audio
#It does not set which card is the default, it configures the device itself.
[Onboard]
volume=0db
#Controls where the onboard analog device routes sound.
#Available options: auto, analog, hdmi
output=auto
EOF

cat << 'EOF' > /usr/bin/ember-manage-audio.py
#!/usr/bin/python3
import subprocess,configparser
config = configparser.ConfigParser()
config.read('/sketch/config/sound.ini')

vol = config['Onboard']['volume']
interface = config['Onboard']['output'].lower()

interfaces={
    "auto": 0,
    "analog": 1,
    "hdmi": 2
}

interface= interfaces[interface]

subprocess.check_call(["amixer", "cset", "numid=3", str(interface)])
#Expects a value in db, like "0db"
subprocess.check_call(["amixer","-c","0", "set", "PCM", vol])
EOF

chmod 744 /usr/bin/ember-manage-audio.py



cat << EOF > /etc/systemd/system/ember-manage-audio.service
[Unit]
Description=Manage audio
After=sysinit.target


[Service]
Type=oneshot
ExecStart=/usr/bin/ember-manage-audio.py

[Install]
WantedBy=sysinit.target

EOF

chmod 744  /etc/systemd/system/ember-manage-audio.service
systemctl enable ember-manage-audio.service
