#!/usr/bin/env bash

# Source error handling, leave this in place
set -x
set -e


#All this does is makes the hostname configurable via /boot

source /common.sh

echo "embedpi" > /sketch/config/hostname



#Put a default in the sketch folder
cat << EOF > /sketch/config/hosts
127.0.0.1   localhost
127.0.1.1   embedpi
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters
EOF

cat << EOF > /sketch/config/filesystem/emberos_hosts.yaml
#This relies on the fact that the OS already configures this to be 0755
/sketch/config:
    bindfiles:
        hosts: /etc/hosts
        hostname: /etc/hostname
EOF



#Hack alert! We do in fact bind mount the /etc/hostname file.
#This lets us get the hostame set up in very early boot.
cat << EOF > /etc/systemd/system/ember-load-hostname.service
[Unit]
Description=Load the hostname
After=systemd-remount-fs.service 
Before=sysinit.target fs_bindings.service systemd-hostnamed.service yggdrasil.service NetworkManager.service nodered.service kaithem.service smbd.service nmbd.service serviceconfig.service apache2.service
RequiresMountsFor=/sketch/
DefaultDependencies=no

[Service]
Type=oneshot
ExecStart=hostname --file /sketch/config/hostname

[Install]
WantedBy=sysinit.target
EOF

systemctl enable ember-load-hostname.service