#!/usr/bin/env bash

# Source error handling, leave this in place
set -x
set -e


#All this does is makes the hostname configurable via /boot

source /common.sh

echo "embedpi" > /etc/hostname



#Put a default in the sketch folder
cat << EOF > /etc/hosts
127.0.0.1   localhost
127.0.1.1   embedpi
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters
EOF
