site-data-dir: /home/pi/kaithem
ssl-dir: /home/pi/kaithem/ssl
save-before-shutdown: yes
run-as-user: root
autosave-state: 6 hours
worker-threads: 16
http-thread-pool: 4
https-thread-pool: 16

#The port on which web pages will be served. The default port is 443, but we use 8001 in case you are running apache or something.
https-port : 8001
#The port on which unencrypted web pages will be served. The default port is 80, but we use 8001 in case you are running apache or something.
http-port : 8002

audio-paths:
    - /usr/share/tuxpaint/sounds
    - /var/public.media/
    - __default__
