#Creates the tmpfs overlay on top of /home/pi
__tmpfsoverlay__HOMEPI:
    bindat: /home/pi
    mode: '750'
    user: pi

/sketch/home/pi:
    #We want to be able to stash security keys in there, so this must be mode
    #700
    mode: '0700'
    user: pi
    #The tmpfs overlay has to be under the sketch stuff, or it seems to point at the original home dir,
    #and cover up the sketch
    #Once the sketch and the bindat is there we can run this and copy anything we might need
    post_cmd: cp -ar /home/pi/persist/.home_template/. /home/pi
    bindat: /home/pi/persist