#!/bin/bash

# Must run AFTER youmightneedit 

set -x
set -e

source /common.sh

unpack /filesystem/pi /home/pi



#For ubuntu server
# apt install -y xserver-xorg xfce4 xfce4-goodies
# dpkg-reconfigure lightdm

# sudo apt-get -y install libgles2-mesa libgles2-mesa-dev xorg-dev


sudo apt-get -y install meson ninja-build

if [ ! -d /build_cache/suru-icon-theme ]; then
   cd /build_cache
   git clone --depth 1 https://github.com/snwh/suru-icon-theme.git
fi

cd /build_cache/suru-icon-theme

# build
meson "build" --prefix=/usr
# install
sudo ninja -C "build" install

cp /build_cache/suru-icon-theme/COPYING /usr/share/icons/Suru
cp /build_cache/suru-icon-theme/README.md /usr/share/icons/Suru



# Xsession errors is a big offender for wrecking down your disk with writes
sed -i s/'ERRFILE=\$HOME\/\.xsession\-errors'/'ERRFILE\=\/var\/log\/\$USER\-xsession\-errors'/g /etc/X11/Xsession

cat << EOF > /etc/logrotate.d/xsession
/var/log/pi-xsession-errors {
  rotate 2 
  daily
  compress
  missingok
  notifempty
}
EOF
! rm  /home/pi/.xsession-errors
# Make it look like it's in the same place so we can get to it easily
ln -s /var/log/pi-xsession-errors /home/pi/.xsession-errors

mkdir -p /sketch/profiles/default/home/pi/.config/autostart/

cat << EOF > /sketch/profiles/default/home/pi/.config/autostart/ember-kiosk.desktop
[Desktop Entry]
Name=EmberDefaultKiosk
Type=Application
Exec=/usr/bin/ember-kiosk-launch.sh http://localhost &
Terminal=false
EOF

cat << EOF > /sketch/profiles/default/home/pi/.config/autostart/ember-autorestart-kiosk.desktop
[Desktop Entry]
Name=EmberAutoRestartKiosk
Type=Application
Exec=  bash -c "while :;  /usr/bin/ember-kiosk-launch.sh http://localhost; done"
Terminal=false
Hidden=true
EOF



cat << EOF > /sketch/profiles/default/home/pi/.config/autostart/unclutter.desktop
[Desktop Entry]
Name=Unclutter
Type=Application
Exec=unclutter
Terminal=false
EOF



cp /filesystem/klaunch.sh /usr/bin/ember-kiosk-launch.sh
chmod 755 /usr/bin/ember-kiosk-launch.sh