#!/bin/bash

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+"$LD_LIBRARY_PATH:"}/usr/lib/libeatmydata
export LD_PRELOAD=${LD_PRELOAD:+"$LD_PRELOAD "}libeatmydata.so

! apt purge -y valgrind

! apt purge -y wolfram-engine wolframscript
! apt purge -y sonic-pi-samples
! apt purge -y libreoffice-base libreoffice-math 
! apt purge -y libreoffice-help-common libreoffice-help-en-us
apt-get -y install libreoffice-draw libreoffice-writer libreoffice-calc
! apt purge -y nuscratch
! apt purge -y scratch2
! apt purge -y scratch3
! apt purge -y scratch
! apt purge -y minecraft-pi
! apt purge -y python-minecraftpi
! apt purge -y realvnc-vnc-viewer
! apt purge -y gpicview
! apt purge -y oracle-java8-jdk
! apt purge -y oracle-java7-jdk
! apt purge -y tcsh
! apt purge -y nodejs-doc
! apt purge -y smartsim

# Old versions
! apt purge -y gcc-7
! apt purge -y gcc-8
! apt purge -y gcc-9

! apt purge -y ^dillo$  ^idle3$  ^smartsim$ ^sonic-pi$  ^epiphany-browser$  ^python-minecraftpi$ ^bluej$ 
! apt purge -y ^greenfoot$  ^greenfoot-unbundled$  ^claws-mail$ ^claws-mail-i18n$

! apt purge -y code-the-classics
! apt purge -y openjdk-11-jdk
! apt purge -y openjdk-11-jdk-headless
! apt purge -y bluej

pip3 uninstall mu-editor

! rm -r /opt/Wolfram
! rm -r /usr/share/code-the-classics
! rm -r /home/pi/MagPi/*.pdf
! rm -r /home/pi/Bookshelf/Beginners*.pdf

apt autoremove -y --purge

# Cover some of the most common
if [ -z "$EMBER_MICRO" ]
then
echo "Not in micro mode"
else
! apt purge -y libreoffice

sudo locale-gen --purge en_US.UTF-8 en_GB.UTF-8 en_HK.UTF-8 zh_CN.UTF-8 zh_TW.UTF-8 hi_IN.UTF-8 ru_RU.UTF-8 es_ES.UTF-8 es_MX.UTF-8 fr_FR.UTF-8 af_ZA.UTF-8 ar_SA.UTF-8
fi