#!/bin/bash
! apt purge -y ^wolfram-engine$ ^sonic-pi-samples$ ^midori$ ^netsurf-gtk$

#Everyhting aside from scratch3 official can go
! apt purge -y ^nuscratch$  ^scratch2$ ^scratch$  ^minecraft-pi$ ^python-minecraftpi$

! apt purge -y ^dillo$  ^idle3$  ^smartsim$ ^sonic-pi$  ^epiphany-browser$  ^python-minecraftpi$ ^bluej$ 
! apt purge -y ^greenfoot$  ^greenfoot-unbundled$  ^claws-mail$ ^claws-mail-i18n$


apt autoremove -y --purge

