#!/bin/bash
! apt purge -y wolfram-engine wolframscript thonny
! apt purge -y sonic-pi-samples

#Everyhting aside from scratch3 official can go
! apt purge -y nuscratch
! apt purge -y scratch2
! apt purge -y scratch
! apt purge -y minecraft-pi
! apt purge -y python-minecraftpi

! apt purge -y ^dillo$  ^idle3$  ^smartsim$ ^sonic-pi$  ^epiphany-browser$  ^python-minecraftpi$ ^bluej$ 
! apt purge -y ^greenfoot$  ^greenfoot-unbundled$  ^claws-mail$ ^claws-mail-i18n$

! rm -r /opt/Wolfram
! rm -r /usr/share/code-the-classics
! rm -r /home/pi/MagPi/*.pdf

apt autoremove -y --purge

# Cover some of the most common
if [ -z "$EMBER_MICRO" ]
then
echo "Not in micro mode"
else
! apt purge -y scratch3
! apt purge -y libreoffice

sudo locale-gen --purge en_US.UTF-8 en_GB.UTF-8 en_HK.UTF-8 zh_CN.UTF-8 zh_TW.UTF-8 hi_IN.UTF-8 ru_RU.UTF-8 es_ES.UTF-8 es_MX.UTF-8 fr_FR.UTF-8 af_ZA.UTF-8 ar_SA.UTF-8
fi