#!/bin/bash
source /common.sh

#Make a dummy self signed certificateZ
if [ ! -f /sketch/kaithemssl/certificate.key] ; then
    mkdirs /sketch/kaithemssl/
    #Look at this race condition here! Someone could steal that private key before we chmod it!
    openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /sketch/kaithemssl/certificate.key  -out  /sketch/kaithemssl/certificate.cert -subj '/CN=localhost'
fi

unpack /filesystem/KaithemAutomation /sketch/kaithem_install/
unpack /filesystem/systemd/ /usr/lib/systemd/system/
unpack /filesystem/KaithemAutomation/kaithem/var /sketch/kaithem
unpack /filesystem/kaithem_sketch /sketch/kaithem


systemctl enable kaithem.service
